from datetime import datetime
from sqlalchemy import Column, Integer, String, Float, Text, DateTime, ForeignKey, Boolean
from sqlalchemy.orm import declarative_base, relationship

Base = declarative_base()

class Review(Base):
    """Raw and preprocessed user app reviews"""
    __tablename__ = 'reviews'

    id = Column(Integer, primary_key=True, autoincrement=True)
    app_name = Column(String(100), nullable=False, default="SampleApp")
    app_version = Column(String(20), nullable=True)
    author = Column(String(100), nullable=True)
    review_text = Column(Text, nullable=False)
    cleaned_text = Column(Text, nullable=True)
    rating = Column(Integer, nullable=False)
    review_date = Column(DateTime, default=datetime.utcnow)
    is_processed = Column(Boolean, default=False)

    # Relationship to sentiment prediction
    sentiment = relationship("SentimentAnalysis", back_populates="review", uselist=False, cascade="all, delete-orphan")

    def __repr__(self):
        return f"<Review(id={self.id}, rating={self.rating}, app_version='{self.app_version}')>"


class SentimentAnalysis(Base):
    """BERT model sentiment predictions and aspect tagging"""
    __tablename__ = 'sentiment_analysis'

    id = Column(Integer, primary_key=True, autoincrement=True)
    review_id = Column(Integer, ForeignKey('reviews.id'), nullable=False, unique=True)
    sentiment_label = Column(String(20), nullable=False)  # Positive, Negative, Neutral
    sentiment_score = Column(Float, nullable=False)        # Confidence score (0.0 to 1.0)
    aspect_category = Column(String(50), nullable=False)   # Bug/Crash, UI/UX, Performance, Pricing, Feature Request, General
    processed_at = Column(DateTime, default=datetime.utcnow)

    # Relationship back to Review
    review = relationship("Review", back_populates="sentiment")

    def __repr__(self):
        return f"<SentimentAnalysis(review_id={self.review_id}, sentiment='{self.sentiment_label}', aspect='{self.aspect_category}')>"


class Recommendation(Base):
    """Aggregated insights and prioritized recommendations generated by the engine"""
    __tablename__ = 'recommendations'

    id = Column(Integer, primary_key=True, autoincrement=True)
    aspect_category = Column(String(50), nullable=False)
    urgency_level = Column(String(20), nullable=False)     # High, Medium, Low
    negative_count = Column(Integer, nullable=False)
    avg_rating = Column(Float, nullable=False)
    urgency_score = Column(Float, nullable=False)          # Calculated metric: negative_count * (5 - avg_rating)
    actionable_recommendation = Column(Text, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)

    def __repr__(self):
        return f"<Recommendation(aspect='{self.aspect_category}', urgency='{self.urgency_level}', score={self.urgency_score})>"
